name: 学校信息变更
description: 申请变更已提交的学校信息，请提供准确的变更内容
title: "[学校信息变更]："
labels: ["申请变更信息"]
body:
  - type: markdown
    attributes:
      value: |
        ## 学校信息变更申请
        请填写需要变更的学校信息，仅需填写需要修改的字段。

  - type: input
    id: original_school_name
    attributes:
      label: 原学校名称
      description: 请填写需要变更信息的原学校完整名称
      placeholder: 天津市实验中学
    validations:
      required: true

  - type: input
    id: issue_number
    attributes:
      label: 原信息填报Issue编号
      description: 请填写原始学校信息填报的Issue编号（如：#123）
      placeholder: "#123"
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: 变更类型
      description: 选择信息变更的类型
      multiple: true
      options:
        - 学校基本信息变更
        - 信息中心位置变更
        - 班级大屏设备更新
        - 软件系统变更
        - 其他信息修正
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 变更内容详情
        请在下方填写具体需要变更的内容：

  - type: textarea
    id: school_info_changes
    attributes:
      label: 学校基本信息变更
      description: |
        填写需要变更的学校基本信息，如：
        - 学校名称变更：原名称 → 新名称
        - 学校位置变更：原地址 → 新地址  
        - 学校类型变更：原类型 → 新类型
      placeholder: |
        例如：
        学校位置变更：天津市河西区平山道1号 → 天津市河西区平山道5号
        学校类型变更：完全中学 → 高级中学
      render: text

  - type: textarea
    id: location_changes
    attributes:
      label: 信息中心位置变更
      description: 填写信息中心位置的具体变更内容
      placeholder: |
        例如：
        信息中心位置：思学楼C座5楼501 → 思学楼A座3楼301
      render: text

  - type: textarea
    id: display_changes
    attributes:
      label: 班级大屏设备变更
      description: |
        填写班级大屏设备的变更内容，包括：
        - 大屏类型变更
        - 品牌型号更新
        - 操作系统升级
        - 冰点还原状态变化
      placeholder: |
        例如：
        大屏品牌：科大讯飞 → 华为
        操作系统：Windows 10 Education → Windows 11 Education
        冰点还原：有 → 无
      render: text

  - type: textarea
    id: additional_changes
    attributes:
      label: 其他补充变更
      description: 填写其他需要变更但未在上面列出的信息
      placeholder: |
        例如：
        新增补充信息：学校近期进行了信息化改造...
        更新备注：原备注信息需要更新为...
      render: text

  - type: textarea
    id: change_reason
    attributes:
      label: 变更原因说明
      description: 请详细说明为什么要进行这些信息变更
      placeholder: |
        例如：
        1. 学校搬迁至新校区
        2. 班级大屏设备统一更新换代
        3. 信息系统升级改造
        4. 之前信息填写有误需要修正
      render: text
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: 信息确认
      description: 请确认以下事项
      options:
        - label: 我确认所填写的变更信息真实准确
          required: true
        - label: 我已核对过原始信息填报内容
          required: true
        - label: 我理解虚假信息可能导致申请被拒绝
          required: true

  - type: markdown
    attributes:
      value: |
        ## 注意事项
        - 请确保填写的原学校名称和Issue编号准确无误
        - 变更原因请尽可能详细说明，便于审核人员理解
        - 审核通过后，相关学校信息将会被更新
        - 如有疑问，请在备注中说明
